/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.asiainfo.ocdp.common.protocol;

@SuppressWarnings("all")
/** 山东流处理，中间接口 */
@org.apache.avro.specific.AvroGenerated
public interface OcdpHubProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OcdpHubProtocol\",\"namespace\":\"com.asiainfo.ocdp.common.protocol\",\"doc\":\"山东流处理，中间接口\",\"types\":[{\"type\":\"record\",\"name\":\"FetchTask\",\"doc\":\"传输的抓取 Task 消息, 序列化结果\",\"fields\":[{\"name\":\"taskId\",\"type\":\"string\",\"doc\":\"Task ID\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"Server Message\"},{\"name\":\"success\",\"type\":\"boolean\",\"doc\":\"下载 task 是否成功\"},{\"name\":\"params\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"],\"doc\":\"Task Parameter\"}]},{\"type\":\"record\",\"name\":\"FetchResponse\",\"doc\":\"传输的抓取结果 Task 消息, 序列化结果\",\"fields\":[{\"name\":\"taskId\",\"type\":\"string\",\"doc\":\"Task ID\"},{\"name\":\"exrror\",\"type\":[\"string\",\"null\"],\"doc\":\"Server Message\"},{\"name\":\"statusCode\",\"type\":\"int\",\"doc\":\"是否抓取成功, 状态码\"}]}],\"messages\":{\"getProxyHost\":{\"doc\":\"获取 Codis 代理 Host，分发逻辑可为多种：随机，均衡，最近距离\",\"request\":[{\"name\":\"host\",\"type\":\"string\"}],\"response\":\"string\"},\"getSysConf\":{\"doc\":\"获取数据库配置参数\",\"request\":[{\"name\":\"cond\",\"type\":\"string\"}],\"response\":{\"type\":\"map\",\"values\":\"string\"}}}}");
  /** 获取 Codis 代理 Host，分发逻辑可为多种：随机，均衡，最近距离 */
  java.lang.CharSequence getProxyHost(java.lang.CharSequence host) throws org.apache.avro.AvroRemoteException;
  /** 获取数据库配置参数 */
  java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getSysConf(java.lang.CharSequence cond) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** 山东流处理，中间接口 */
  public interface Callback extends OcdpHubProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.asiainfo.ocdp.common.protocol.OcdpHubProtocol.PROTOCOL;
    /** 获取 Codis 代理 Host，分发逻辑可为多种：随机，均衡，最近距离 */
    void getProxyHost(java.lang.CharSequence host, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /** 获取数据库配置参数 */
    void getSysConf(java.lang.CharSequence cond, org.apache.avro.ipc.Callback<java.util.Map<java.lang.CharSequence,java.lang.CharSequence>> callback) throws java.io.IOException;
  }
}